### PR TITLE
Build index of compiled parsers and add api for file-type resolution

### PR DESCRIPTION
**Pull request by tmm1**
cc https://github.com/grantjenks/py-tree-sitter-languages/issues/21 https://github.com/grantjenks/py-tree-sitter-languages/pull/22

cc @amaanq @simonw @paul-gauthier @grantjenks

### CODE REVIEW

**Comment by amaanq** [comment]
Nice to see! Great timing too because I was thinking of adding more bindings, I've added some for Go, C, and Swift here:
https://github.com/tree-sitter/tree-sitter/pull/2438

I'd like Python and Zig too but I have limited experience in how packaging and that stuff works for those languages

**Comment by amaanq** [comment]
Ci seems to be outdated...

**Comment by amaanq** [comment]
I've added upstream support for python bindings (kinda) in the linked PR, would be nice if you could check it out and provide some feedback

**Comment by ObserverOfTime** [comment]
Closing this since we plan on removing `build_library` in the next version, in favour of pre-compiled wheels for languages, and language detection will not be particularly useful (if even feasible) at that point.

**Pull request closed without merging**
