### PR TITLE
binding/query.c: use PyErr_Format instead of _PyErr_FormatFromCause 

### PR DESCRIPTION
**Pull request by arthurzam**
The `_PyErr_FormatFromCause` function is a private function, which was never documented. While it existed for a long time, it was removed in Python 3.13 https://github.com/python/cpython/issues/106320.

Use instead the public function `PyErr_Format`, which is also part of the stable API.

### CODE REVIEW

**Comment by ObserverOfTime** [comment]
`PyErr_Format` does not include the cause.

**Comment by arthurzam** [comment]
> `PyErr_Format` does not include the cause.

OK, so which other function should we use? I can modify it as needed.

**Comment by arthurzam** [comment]
Thank you. I leave it to your discretion if you want to just close this PR, or override it, or anything else.

**Comment by ObserverOfTime** [comment]
Fixed in 2f7889d

**Comment by chenrui333** [comment]
@ObserverOfTime any chance cutting a new release? Thanks!

**Comment by ObserverOfTime** [comment]
It's in v0.23.1.

**Comment by chenrui333** [comment]
sorry, I missed it, the 0.23.1 works for me, thanks!

**Pull request closed without merging**
