### PR TITLE
Make match captures a dict[str,Node|list[Node]]

### LINKED ISSUE #182: Captures are not grouped
While using the tree-sitter cli, I get a visual representation of grouped queries like below -
```zsh
aayush420@anonymous djangotest % tree-sitter query ../tree-sitter/queries/python/api/django-endpoints.query urls.py
urls.py
  pattern: 0
    capture: urlpatterns, start: (5, 0), end: (9, 1)
    capture: 0 - urlpatternsVarName, start: (5, 0), end: (5, 11), text: `urlpatterns`
    capture: 1 - pathVarName, start: (6, 4), end: (6, 8), text: `path`
    capture: 2 - path, start: (6, 9), end: (6, 11), text: `""`
    capture: 3 - target, start: (6, 13), end: (6, 24), text: `views.index`
    capture: 4 - nameArg, start: (6, 26), end: (6, 38), text: `name="index"`
  pattern: 0
    capture: urlpatterns, start: (5, 0), end: (9, 1)
    capture: 0 - urlpatternsVarName, start: (5, 0), end: (5, 11), text: `urlpatterns`
    capture: 1 - pathVarName, start: (7, 4), end: (7, 8), text: `path`
    capture: 2 - path, start: (7, 9), end: (7, 17), text: `"polls/"`
    capture: 3 - target, start: (7, 19), end: (7, 40), text: `include("polls.urls")`
  pattern: 0
    capture: urlpatterns, start: (5, 0), end: (9, 1)
    capture: 0 - urlpatternsVarName, start: (5, 0), end: (5, 11), text: `urlpatterns`
    capture: 1 - pathVarName, start: (8, 4), end: (8, 8), text: `path`
    capture: 2 - path, start: (8, 9), end: (8, 17), text: `"admin/"`
    capture: 3 - target, start: (8, 19), end: (8, 34), text: `admin.site.urls`

```
But when I use py-tree-sitter and `.captures`, they are just in a single list and are not grouped. Sometimes, the order is also messed up. Is this intended? Or is there a different way to fetch captured groups?

### PR DESCRIPTION
**Pull request by jhandley**
Return the captures of a match as a dict where the key is the capture name and the value is a Node or a list of Nodes. For regular captures, the value is a Node. For captures that can contain multiple nodes because they use a * or + quantifier, the value is a list of Nodes.

---

Closes #182

### CODE REVIEW

**Comment by amaanq** [comment]
Although I agree it'd be nicer to index a Node/Nodes by the capture name, this is a breaking change. Are there any other benefits to use a dict besides that?

**Comment by jhandley** [comment]
> Although I agree it'd be nicer to index a Node/Nodes by the capture name, this is a breaking change. Are there any other benefits to use a dict besides that?

This only changes the API for the matches method, not the captures method. Given that matches has not been implemented yet in the main branch it shouldn't break anything.

The benefit to using the dict is just a simpler API. At least in the code I've written so far, I always want to look up using the name so this avoids writing extra utility functions to search through the list.

**Comment by amaanq** [comment]
Oops sorry, I just noticed it was for matches, yeah this is totally fine

**Comment by jhandley** [comment]
I marked it as ready. Note that is against the [tree-sitter:prepare-bindings](https://github.com/tree-sitter/py-tree-sitter/tree/prepare-bindings) branch, not master.

Let me know if I can help get the matches PR over the finish line. Having matches would be a big help for our current project so I can put some time into it if it would help.

**Comment by jhandley** [comment]
> @jhandley Are you available to rebase this PR once #159 is merged?

Sure. Will do.

**Comment by ObserverOfTime** [comment]
Also note that `|` unions are a Python 3.9 feature and py-tree-sitter will continue to support 3.8 until the next version.

**Comment by amaanq** [comment]
feel free to rebase now @jhandley, sorry for taking so long to get to #159

**Review by ObserverOfTime — APPROVED** [review]
Thank you. This looks good.

**Comment by sgoai** [comment]
Did the [docs](https://github.com/tree-sitter/py-tree-sitter/blame/master/README.md#L270) never get updated for this?

**Comment by maxbrunsfeld** [comment]
Hi, sorry for chiming late here. I don’t think this is an improvement. Having to check, for every usage, whether the values in the dictionary are lists or single nodes is going to make the API more error prone and verbose. The captures within a match have a meaningful order to them, so I think a list of tuples makes more sense than this dictionary of maybe-lists-maybe-nodes.

**Comment by ObserverOfTime** [comment]
> Did the [docs](https://github.com/tree-sitter/py-tree-sitter/blame/master/README.md#L270) never get updated for this?

That is true. I'll update them soon.

> Having to check, for every usage, whether the values in the dictionary are lists or single nodes is going to make the API more error prone and verbose.

The values are always lists now.
https://github.com/tree-sitter/py-tree-sitter/blob/e1649720666d795e70ee5b519cc817c634c1b8aa/tree_sitter/__init__.pyi#L282-L293

**Pull request merged**
