### PR TITLE
Fix issue with multiple predicates

### LINKED ISSUE #92: Queries with multiple predicates fail with RuntimeError
Queries that contain two predicates seem to always fail with a RuntimeError with this message: `Capture predicate must start with a string`.

I tried digging deeper and got a minimal test that reproduces the issue on this PR https://github.com/tree-sitter/py-tree-sitter/pull/91 but I don't have a fix for it yet.

I see that this is a feature introduced recently in https://github.com/tree-sitter/py-tree-sitter/pull/82 and not published on PyPI yet.

Trying this in [the playground](https://tree-sitter.github.io/tree-sitter/playground) works as expected, so I'm thinking it has to be an issue in the Python bindings:

Code:
```javascript
keypair_object = {
    key1: value1,
    equal: equal
}

function fun1(arg) {
    return 1;
}

function fun1(notarg) {
    return 1 + 1;
}

function fun2(arg) {
    return 2;
}
```

Query:
```
(
    (function_declaration
        name: (identifier) @function-name
        parameters: (formal_parameters
            (identifier) @argument-name
        )
    )
    (#eq? @function-name fun1)
    (#eq? @argument-name arg)
)
```

I expect it to match `fun1(arg)` only - which seems to be the case in the playground (only that line's function/argument names are coloured).

cc @ocastejon since you were the author of that PR - would you have any hints/clues about the root cause?

### PR DESCRIPTION
**Pull request by ls-jad-elkik**
WIP Attempt to fix the issues with multiple predicates

Closes #92

### CODE REVIEW

**Comment by ocastejon** [comment]
So after looking at it, it turns out the solution is quite simple: you should change [line 1450 in `tree_sitter/binding.c`](https://github.com/tree-sitter/py-tree-sitter/pull/91/files#diff-a6adb5252016d665f70ccc5cc08b965138ee83044685c0ffe064d8ba4a6a927cL1450) from:
```
predicate_step += predicate_len;
```
to:
```
predicate_step += predicate_len + 1;
```
Otherwise, in the next iteration of the for loop, the first `predicate_step` is still the last one parsed, which is of type `TSQueryPredicateStepTypeDone`, hence the error.

I tried the tests you provided and they all passed (after a minor typo correction, which I'll add as a change suggestion). 

Thanks for catching this!

**Comment by ocastejon** [comment]
@ls-jad-elkik In case you missed it, it looks like checks did not pass because of a line too long in the file `test_tree_sitter.py`, which should be straightforward to fix. I'd like to see this PR merged, it'd be a shame if it wasn't just because of that! :)

**Comment by maxbrunsfeld** [comment]
Should we wait to merge this until you've debugged that issue further? Otherwise, I'm ok merging this as-is.

**Comment by lunixbochs** [comment]
Let's leave this open if there's another multiple-predicate issue outstanding.

**Comment by ls-jad-elkik** [comment]
The issue happens with queries that use `[]`:

So something like:

```
(
    (function_declaration
        name: (identifier) @function-name
        parameters: [
          (formal_parameters
            (identifier) @argument-name-x
            (#eq? @argument-name-x "x")
          )
          (formal_parameters
            (identifier) @argument-name-y
            (#eq? @argument-name-y "y")
          )
    )
    (#eq? @function-name fun1)
)
```

This is a stupid example, but I think it would show the problem: predicates inside one of the `[]` alternatives will fail to evaluate because the capture `@argument-name-y` or `@argument-name-x` would not always be there.

Tried some variations of a patch like this one:

```patch
diff --git a/tree_sitter/binding.c b/tree_sitter/binding.c
index e61de2c..5a6db56 100644
--- a/tree_sitter/binding.c
+++ b/tree_sitter/binding.c
@@ -1132,7 +1132,7 @@ static Node *node_for_capture_index(uint32_t index, TSQueryMatch match, Tree *tr
           return capture_node;
         }
     }
-    PyErr_SetString(PyExc_ValueError, "An error occurred, capture was not found with given index");
+    // PyErr_SetString(PyExc_ValueError, "An error occurred, capture was not found with given index");
     return NULL;
 }
 
@@ -1157,7 +1157,8 @@ static bool satisfies_text_predicates(Query *query, TSQueryMatch match, Tree *tr
       node1 = node_for_capture_index(capture1_value_id, match, tree);
       node2 = node_for_capture_index(capture2_value_id, match, tree);
       if (node1 == NULL || node2 == NULL)
-        goto error;
+        return false;
+//        return true;
       node1_text = node_get_text(node1, NULL);
       node2_text = node_get_text(node2, NULL);
       if (node1_text == NULL || node2_text == NULL)
@@ -1174,7 +1175,8 @@ static bool satisfies_text_predicates(Query *query, TSQueryMatch match, Tree *tr
       uint32_t capture_value_id = ((CaptureEqString *)text_predicate)->capture_value_id;
       node1 = node_for_capture_index(capture_value_id, match, tree);
       if (node1 == NULL)
-        goto error;
+        return false;
+//        return true;
       node1_text = node_get_text(node1, NULL);
       if (node1_text == NULL)
         goto error;
@@ -1189,7 +1191,8 @@ static bool satisfies_text_predicates(Query *query, TSQueryMatch match, Tree *tr
       uint32_t capture_value_id = ((CaptureMatchString *)text_predicate)->capture_value_id;
       node1 = node_for_capture_index(capture_value_id, match, tree);
       if (node1 == NULL)
-        goto error;
+        return false;
+//        return true;
       node1_text = node_get_text(node1, NULL);
       if (node1_text == NULL)
         goto error;
```

But I couldn't spend lots of time on this and I don't think any of those variations are correct.

**Comment by ls-jad-elkik** [comment]
IMO we can merge this, and another issue/PR specifically for Alternations and multiple predicates, unless you feel those two are tightly related.

**Comment by ls-jad-elkik** [comment]
> Yeah, that isn’t a Python binding issue. It’s actually the expected behavior, as predicates are not associated with particular locations within a pattern, but are rather associated with the pattern as a whole. It’s good feedback though; I’ve heard before that it is unexpected.

On the online playground it looks like it works as expected, that's why I was assuming it's a Python binding issue.

**Pull request merged**
