### PR TITLE
Add typing information

### PR DESCRIPTION
**Pull request by DorianCzichotzki**
Greate work on tree-sitter and the python binding. The only issue I found was, that there are no type hints. That makes it very hard to work with the package.

I created this PR to add a stub file containing the type definitions for the C extension. This should help tools like mypy and IDEs to show docstrings and provide better code completion support.
I hope the definitions are complete.

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
This is great. Is there a command we can run on CI that checks that the tests conform to the types declared in this file?

**Comment by lunixbochs** [comment]
Note there's another type stub I linked in this issue: https://github.com/tree-sitter/py-tree-sitter/issues/58

**Comment by DorianCzichotzki** [comment]
@lunixbochs Sry did not see that. 

@maxbrunsfeld I added mypy to check the test_tree_sitter.py module.

**Comment by DorianCzichotzki** [comment]
I had to remove the mypy test for pypy. The typed-ast package is not able to build under pypy3.7 (see https://github.com/python/typed_ast/issues/111).

**Comment by maxbrunsfeld** [comment]
Ok, I approved it so it's running and we can see if the CI passes.

@lunixbochs You're more familiar with Python tooling. Do you like this solution for adding types? I'm cool with it, since it seems to pass on CI.

**Comment by DorianCzichotzki** [comment]
Is there something missing or anything I can do to get it merged?

**Comment by lunixbochs** [comment]
@DorianCzichotzki were these manually written? I believe you don't need the `...` if you also have a docstring.

**Comment by NorthIsUp** [comment]
what is needed for this to merge, it would be super helpful!

**Comment by lunixbochs** [comment]
I just need to find some time to merge the two approaches and update the stubs.

**Comment by synek** [comment]
Any update on this PR? I'd also like to use it :)

**Comment by Akuli** [comment]
I added tree-sitter stubs to typeshed. Run `pip install types-tree-sitter` to use them.

It would still be preferable to have them here, but it's a relatively small package, so typeshed will also do a good job of maintaining the stubs if the types never make it to py-tree-sitter.

**Comment by amaanq** [comment]
Superseded by #150

**Pull request closed without merging**
